name = "screendle"
pages_build_output_dir = ".svelte-kit/cloudflare"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "screendle-db"
database_id = "4b5e7481-ca5a-46c9-969e-205d64c30ea3"
